### ISSUE TITLE
Excavator gets confused.  Solved by re-painting leveling designation.

### ISSUE THREAD

**Issue by super-aardvark** [MaFi-Games/Captain-of-Industry-issues#1057]
### Issue description

Excavator gets stuck, taking no action while cycling through various statuses (Loading cargo, Searching for a valid terrain designation, Driving to destination).  Re-painting the leveling designation (not sure if it can occur with a mining designation) over the existing one solves the issue.

I mentioned this in a comment in #1052, but after observing it several more times I'm putting it in its own issue.  (See there for an additional save file showing the issue.)

### Expected behavior

Excavator should continue working normally.  Re-applying a designation without changing the type/level/contour shouldn't ever have any effect.

### Reproduction steps

1. Load the attached save.
2. Click the excavator to see the status cycling.
3. Press N
4. Drag along the existing designation to re-apply it.
5. Observe: excavator resumes operation.

### Game version

0.5.1 (200)

### Attachments

[excavator-bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11646129/excavator-bug.zip)

**Comment by MaFi-Games** [comment]
Thanks for the report and save file, this was fixed in v0.5.1a.

**Comment by super-aardvark** [comment]
Encountered the issue again, on 0.5.1a.  With a mining designation this time.  Re-painting the mining designation doesn't solve it.  Painting a leveling designation over the top fixes it; switching back to mining designation immediately causes the problem again.  (After letting it mine a couple scoops with leveling designation, switching back to mining is fine.)

[excavator-bug-continues.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11660863/excavator-bug-continues.zip)
