### ISSUE TITLE
Dumping designations adjacent to retaining walls do not seem to be properly detected.

### ISSUE THREAD

**Issue by rhodesm** [MaFi-Games/Captain-of-Industry-issues#1270]
### Issue description

 Truck will not finish filling dumping designation next to wall. When a dumping designation is placed next to an existing retaining wall the designation will be filled, but not completely. at a certain point the designation becomes "greyed out"and trucks stop dumping there.

Even after deleting and recreating the dumping designation, it will not properly detect that the spot needs to be filled. I have also tried enabling and disabling the "toggle_terrain_designations_over_entities" without any success. The only way to get the void filled is to deleted the adjacent wall. This seems like a recent regression as I do not recall this occurring prior to v0.5.4f although I have not tested that.

### Reproduction steps

Load attached save. Check dumping designations.

### Game version and build number

v0.5.4.g (b244)

### Operating system

Windows

### Attachments

[fill issue.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12570694/fill.issue.zip)
![Screenshot 2023-09-10 162739](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/12317834/3592a8ee-2193-481d-bd0b-89ef83edb7e1)
![Screenshot 2023-09-10 162805](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/12317834/2ed426f2-715a-4c94-820d-d49f1eb3b2ef)
![Screenshot 2023-09-10 162814](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/12317834/68abf8eb-a4f3-44b5-adb0-de3abb5c6b96)

**Comment by zuff-coi** [comment]
This probably is related to the change we made a while back preventing designating on retaining walls and not being able to build retaining walls on designations. Thanks for reporting

**Comment by rhodesm** [comment]
That is kinda what I suspected as well, so I have also tried it after the "toggle_terrain_designations_over_entities"  setting enabled and disabled without any success.

**Comment by Identifier** [comment]
I'd also love to make the terrain perfectly flat against retaining walls.  I understand that terrain designations are fixed to a 4x4 world grid, and that probably won't change, but I hope the fix for this will re-enable terrain designations over retaining walls, especially if you could have a retaining wall straddle the 4x4 boundary (i.e. half of the retaining wall is on one designation, and the other half is on the other designation), so that you can have both sides of the wall perfectly flat against different-height terrains.

**Comment by rodelle** [comment]
Commenting here because I'm still seeing this issue with my giant retaining wall on build v0.5.5d (b260).
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/839150/a658acbf-53b9-406b-ac7e-22663b455843)
