### ISSUE TITLE
(Gamebreaking) Vehicles not refueling despite fuel stations

### ISSUE THREAD

**Issue by jcrites** [MaFi-Games/Captain-of-Industry-issues#1406]
### Issue description

I have multiple fuel stations full of fuel, and trucks assigned to them. Despite this, excavators and tree harvesters are saying that they have no fuel.

The truck assigned to the fuel station says that it has no jobs, despite those other vehicles being out of fuel. The fuel stations are also set to allow all vehicles to refuel there.

![20240408132848_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/88504/e4fbef46-175c-41ed-9977-8dfed533fa4f)

### Reproduction steps

Load attached save and observe the notifications from vehicles saying they're out of fuel

### Game version and build number

v0.6.0c (b319)

### Operating system

Windows

### Attachments

[save.ZIP](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14910676/save.ZIP)

**Comment by jcrites** [comment]
I think this was fixed by the recent patch FYI

**Comment by zersal** [comment]
It's not fixed, I had this happen on a new game yesterday, 2 excavators would just constantly forget they need fuel. Pausing them or moving them seems to make them remember. Or sometimes randomly they would remember.
I haven't seen this happening after getting refuelling stations and moving the 2 buggy excavators that were not being refuelled to fix them.
Here in this save you can see the copper excavator just sitting there and running out of fuel, the iron one will do the same a while later.
[24-10-28_04-52-autosave-paused.zip](https://github.com/user-attachments/files/17561248/24-10-28_04-52-autosave-paused.zip)
