### ISSUE TITLE
Blast Furnace is 3x more expensive to upgrade than to build from scratch

### ISSUE THREAD

**Issue by lowstrife** [MaFi-Games/Captain-of-Industry-issues#180]
Pretty self-explanatory - no idea how to reproduce it or what caused it... it's been like this ever since I researched the tech and upgraded my blast furnaces. Obviously I would expect the upgrade cost to be in line with other upgrades (where it's cheaper rather than more expensive).

I've actually paid to upgrade them - I can confirm it does take 540 to complete the upgrade. 

![image](https://user-images.githubusercontent.com/65734844/171689917-3c1e0e8b-2727-49eb-975b-117f50c9752c.png)

[blast furnace.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8826213/blast.furnace.zip)

[22-05-31_11-07-33_9968.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8826215/22-05-31_11-07-33_9968.log)

**Comment by MaFi-Games** [comment]
Thanks for the report. This has been fixed v0.4.1a.

**Comment by lowstrife** [comment]
Still not fixed. Just relaunched and patched my game to 0.4.1e

![image](https://user-images.githubusercontent.com/65734844/172071366-b19277d2-9c5c-4a02-b780-0f5e872e3771.png)
