### ISSUE TITLE
Replacing vehicles fails to use all reasonable and available depots

### ISSUE THREAD

**Issue by jjerhub** [MaFi-Games/Captain-of-Industry-issues#1928]
When replacing vehicles I would expect it to use all available depots and balance between them especially if the two depots are right next to one another.

Presently they all get queued in one depot, perhaps unless that depot's queue is full (I didn't verify that last part)

![Image](https://github.com/user-attachments/assets/b1877145-21e4-40f1-b21f-29a6d398230f)

**Comment by jjerhub** [comment]
Slight correction, I just reached a full queue to where it shows a +X and its still queueing to the same depot.

**Comment by MaFi-Games** [comment]
Just tested, and in my case, both vehicle depots are used for the replacements. I'm not sure if we fixed it before or if it is something different. But if you have a save that can reproduce this, please drop it here so we can take a look.

**Comment by jjerhub** [comment]
Okay, I'll try to replicate in latest build

**Comment by jjerhub** [comment]
I made a quick test file using CoI Extended's creative mode, and its still happening for me on 0.7.8a (b486)  (added .zip extension since ".save" not supported for upload)

1) Build two vehicle depots side-by-side.
2) Produce like 10 T1 trucks
3) Once those have finished queue them for upgrade to T2
4) Note that only the nearest depot is used instead of balancing between the two side-by-side depots

[save.save.zip](https://github.com/user-attachments/files/21873626/save.save.zip)
