### ISSUE TITLE
Ocean visible when digging out filled ocean area

### ISSUE THREAD

**Issue by Burnrate** [MaFi-Games/Captain-of-Industry-issues#53]
**Describe the issue**
When an ocean tile is filled in, you can later dig it out again if is surrounded by land.  The water object will still be there.

**To Reproduce**
1. Fill in ocean and surrounding tiles
2. Dig out an area that was ocean but is now surrounded by land.
3. Dug out area shows water still

**Expected behavior**
Ocean should somehow propagate from outside the island and not be static.

**Additional context**
 - Game version: 0.2.12

**Attachments**
Save file attached.

![image](https://user-images.githubusercontent.com/2849955/136676557-6ebd2408-e24d-4bb7-b279-c46585654027.png)

[G6.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7316580/G6.zip)

**Comment by MaFi-Games** [comment]
Thanks for reporting this. Unfortunately ocean only recomputes after load, we need to make this more dynamic.

For now, save&load should fix this.

**Comment by cy-one** [comment]
At least in my case, save&load does not help.
![20220109151546_1](https://user-images.githubusercontent.com/12306560/148686282-07c8c027-63c5-4637-a12b-5076a8ff8742.jpg)

This occurred yesterday. I loaded an autosave (did not manually save) just a few minutes ago and took that screenshot.

**Comment by TumultuousTitan** [comment]
![22-02-20_00-30-40_3126_photo](https://user-images.githubusercontent.com/8948527/154834982-409fb659-32b5-49e5-9ef4-f27d8fc201c2.png)
This still occurs version 0.3.11f. Tried reloading and did not fix the issue. This is mined terrain, not filled in ocean.

[Ocean Bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8103651/Ocean.Bug.zip)

**Comment by MaFi-Games** [comment]
Thanks for you report. This has been fixed in one of our previous updates.
