### ISSUE TITLE
Trucks pause too long in between excavation job (late game)

### ISSUE THREAD

**Issue by marcrhoule** [MaFi-Games/Captain-of-Industry-issues#596]
### Issue description

Gets loaded with Copper or Iron, waits a minute, then dumps in the nearby storage, waits another minute then resumes. 

### Expected behavior

be fast like the beginning of the game and not kill my spirit.

### Reproduction steps

https://www.dropbox.com/s/ty4oqy8g0gxhmyr/Captain%20of%20Industry%202022-07-17%2016-55-13.mp4?dl=0

### Game version

0.4.8

**Comment by MaFi-Games** [comment]
Please provide a save file of this issue happening.

**Comment by marcrhoule** [comment]
[save_22-07-17_17-13-12.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9127986/save_22-07-17_17-13-12.zip)

**Comment by ParanoikCZE** [comment]
I would say that this might be caused just by overall performance. Can you try to run the game on normal speed for a while? Is it better?

**Comment by marcrhoule** [comment]
Same - maybe this helps... 

![Screenshot (25)](https://user-images.githubusercontent.com/79425118/179417006-b5e41a4f-e162-45f2-be5b-605e5917c2cc.png)

**Comment by MattMills** [comment]
[save_22-07-22_13-03-19.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9170079/save_22-07-22_13-03-19.zip)
save attached, I am experiencing this heavily in all trucks, they seem to "stall" frequently and they all show "queued and waiting", then they all move at the same time a tiny bit, and it happens again over and over.

**Comment by zuff-coi** [comment]
> [save_22-07-22_13-03-19.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9170079/save_22-07-22_13-03-19.zip) save attached, I am experiencing this heavily in all trucks, they seem to "stall" frequently and they all show "queued and waiting", then they all move at the same time a tiny bit, and it happens again over and over.

Please try the [latest experimental](https://steamcommunity.com/games/1594320/announcements/detail/3397421255147457180) update we released yesterday which addresses these issues and let me know if that resolves it for you.

**Comment by MattMills** [comment]
Appears to be resolved for me, at least, I haven't seen any vehicles pausing like they were.

**Comment by MaFi-Games** [comment]
Unfortuantely in save "save_22-07-17_17-13-12" I can still see the PF struggling a bit. It is probably better but there are still visible delays in iron and copper mines.

**Comment by MaFi-Games** [comment]
I believe we have fixed this as approx. a month ago we improved the performance of our PF significantly.
